//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 11:30:02 AM IST 
//


package com.zetagile.foodcart.dto;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Product implements Serializable {

    private static final long serialVersionUID = -8414229179291216957L;


    protected List<Property> property;

    protected String productId;

    protected String categoryId;


    public List<Property> getProperty() {
        if (property == null) {
            property = new ArrayList<Property>();
        }
        return this.property;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String value) {
        this.productId = value;
    }

    public String getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(String value) {
        this.categoryId = value;
    }

}
